## Fake News Classifier Using LSTM

## Dataset: https://www.kaggle.com/c/fake-news/data#

In [47]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [48]:
df=pd.read_csv("train.csv")

In [49]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [50]:
df.shape

(20800, 5)

In [51]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

## Drop Nan Values

In [52]:
df=df.dropna()

In [53]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [54]:
df.shape

(18285, 5)

## Get the Independent Features

In [55]:
X=df.drop("label",axis=1)

In [56]:
X.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...

## Get the Independent Features

In [57]:
y=df["label"]

In [58]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: label, dtype: int64

In [59]:
X.shape

(18285, 4)

In [60]:
y.shape

(18285,)

In [61]:
import tensorflow as tf

In [62]:
tf.__version__

'2.9.1'

In [63]:

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence  import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense


### Vocabulary size


In [64]:
voc_size=5000

## Onehot Representation

In [65]:
messages=X.copy()

In [66]:
messages.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...

In [67]:
messages["title"][0]

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It'

In [68]:
messages["author"][0]

'Darrell Lucus'

### only we r going to work on title column (one hot encoding)

### messages.reset_index(inplace=True) not important 

In [69]:
messages.reset_index(inplace=True)

In [70]:
messages.head()

index  id                                              title  \
0      0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2   2                  Why the Truth Might Get You Fired   
3      3   3  15 Civilians Killed In Single US Airstrike Hav...   
4      4   4  Iranian woman jailed for fictional unpublished...   

               author                                               text  
0       Darrell Lucus  House Dem Aide: We Didn’t Even See Comey’s Let...  
1     Daniel J. Flynn  Ever get the feeling your life circles the rou...  
2  Consortiumnews.com  Why the Truth Might Get You Fired October 29, ...  
3     Jessica Purkiss  Videos 15 Civilians Killed In Single US Airstr...  
4      Howard Portnoy  Print \nAn Iranian woman has been sentenced to...

## now implement Stop words and stemming

In [71]:
import nltk
import re
from nltk.corpus import stopwords

In [72]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Afzal\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

### Dataset Preprocessing

In [73]:

from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [1]:
corpus

NameError: name 'corpus' is not defined

In [75]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

### Onehot Representation

In [76]:
onehot_repr=[one_hot (words,voc_size)for words in corpus]
onehot_repr

[[3588, 3687, 122, 4995, 956, 3628, 3465, 3357, 1762, 4459],
 [962, 2133, 4922, 4161, 575, 1043, 2786],
 [3248, 4614, 2116, 160],
 [24, 322, 2216, 2265, 2188, 1850],
 [2097, 575, 1062, 1645, 1481, 2169, 575, 1983, 4446, 993],
 [1272,
  3245,
  4169,
  492,
  1196,
  3143,
  4324,
  36,
  1004,
  1433,
  180,
  415,
  2021,
  1700,
  2786],
 [3749, 2563, 2348, 1283, 2090, 1519, 2526, 1555, 2677, 2752, 3809],
 [3035, 4878, 2566, 342, 2347, 399, 3143, 4091, 2677, 2752, 3809],
 [488, 2775, 3173, 4383, 329, 1133, 2807, 4792, 3143, 1602],
 [4417, 1963, 3668, 950, 1765, 2065, 695, 1115],
 [216, 2452, 1942, 3094, 2147, 4218, 4652, 1146, 1420, 2358, 213],
 [2265, 117, 956, 1133, 3143, 2347],
 [3871, 1675, 1823, 85, 2658, 258, 450, 1318, 3076],
 [1461, 3300, 1164, 3295, 4699, 136, 646, 2677, 2752, 3809],
 [3872, 4891, 1589, 4146, 1571, 2677, 2752, 3809],
 [209, 1795, 4264, 671, 3689, 4057, 2457, 4664, 4478, 604],
 [4963, 1603, 2133],
 [2496, 4817, 3650, 720, 3143, 298, 1427, 2786],
 [1445, 773, 

In [77]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [78]:
onehot_repr[1]

[962, 2133, 4922, 4161, 575, 1043, 2786]

## Embedding Representation

### all the sentence has diffrent length so we have to make equal size

### so the labirary w r going to use padding

In [111]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)




[[3588 3687  122 ...    0    0    0]
 [ 962 2133 4922 ...    0    0    0]
 [3248 4614 2116 ...    0    0    0]
 ...
 [2451 4603 4392 ...    0    0    0]
 [ 676 2347 3772 ...    0    0    0]
 [1955 1868 4543 ...    0    0    0]]


In [112]:
embedded_docs[0]

array([3588, 3687,  122, 4995,  956, 3628, 3465, 3357, 1762, 4459,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0])

In [113]:
voc_size

5000

## Creating model

In [114]:

embedding_vector_features=40 ##features representation (every index will be represented by 40 feture with some diffrent diffrent values )
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))    # neuron 
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 20, 40)            200000    
                                                                 
 lstm_3 (LSTM)               (None, 100)               56400     
                                                                 
 dense_3 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [115]:
len(embedded_docs),y.shape

(18285, (18285,))

In [116]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [117]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

## now split data into training and test 

In [118]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

### Model Training

In [119]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 20s 73ms/step - loss: 0.3065 - accuracy: 0.8558 - val_loss: 0.2040 - val_accuracy: 0.9133
Epoch 2/10
192/192 [==============================] - 9s 49ms/step - loss: 0.1299 - accuracy: 0.9506 - val_loss: 0.1968 - val_accuracy: 0.9220
Epoch 3/10
192/192 [==============================] - 9s 49ms/step - loss: 0.0876 - accuracy: 0.9702 - val_loss: 0.2301 - val_accuracy: 0.9213
Epoch 4/10
192/192 [==============================] - 9s 45ms/step - loss: 0.0590 - accuracy: 0.9795 - val_loss: 0.2133 - val_accuracy: 0.9173
Epoch 5/10
192/192 [==============================] - 9s 49ms/step - loss: 0.0425 - accuracy: 0.9852 - val_loss: 0.2869 - val_accuracy: 0.9181
Epoch 6/10
192/192 [==============================] - 10s 54ms/step - loss: 0.0268 - accuracy: 0.9905 - val_loss: 0.3854 - val_accuracy: 0.9095
Epoch 7/10
192/192 [==============================] - 10s 54ms/step - loss: 0.0192 - accuracy: 0.9944 - val_loss: 0.3611 - val_accuracy: 0.9

### add dropout to improve the accuracy of the model (your wish)

In [88]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_len))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

## Performance Metrics And Accuracy

In [120]:
y_pred=model.predict(X_test)


189/189 [==============================] - 3s 11ms/step


### now when we have value greater the .5 we will cosider as 1 and when we have value less then o.5 we will cosider as 0

In [121]:
y_pred=np.where(y_pred > 0.5, 1,0) ##AUC ROC Curve

In [122]:
# y_predd=[]

# for i in y_pred:
#     if i>0.5:
#         y_predd.append(1)
#     else:
#         y_predd.append(0)

In [123]:
y_pred.shape

(6035, 1)

In [124]:
y_test.shape

(6035,)

In [125]:
from sklearn.metrics import confusion_matrix

In [126]:
confusion_matrix(y_test,y_pred)

array([[3139,  280],
       [ 255, 2361]], dtype=int64)

In [127]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9113504556752279

In [128]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.92      0.92      3419
           1       0.89      0.90      0.90      2616

    accuracy                           0.91      6035
   macro avg       0.91      0.91      0.91      6035
weighted avg       0.91      0.91      0.91      6035

